# Generated by Django 4.2.11 on 2024-08-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='Receipe_description',
            new_name='Receipe_dics',
        ),
    ]
