# Generated by Django 4.2.11 on 2024-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='Receipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
